project_name: homebox-export

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/homebox-export
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/kusold/homebox-export:v{{ .Version }}"
      - "ghcr.io/kusold/homebox-export:v{{ .Major }}"
      - "ghcr.io/kusold/homebox-export:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/kusold/homebox-export:latest"
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files: []

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: kusold
    name: homebox-export
  draft: true
  prerelease: auto
  mode: replace
  header: |
    ## homebox-export {{ .Version }} ({{ .Date }})

    See the full changelog [here](https://github.com/kusold/homebox-export/blob/main/CHANGELOG.md)

    ### Docker Images
    ```bash
    docker pull ghcr.io/kusold/homebox-export:{{ .Version }}
    ```
  footer: |
    **Full Changelog**: https://github.com/kusold/homebox-export/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Thanks!
    For more information, please check the [documentation](https://github.com/kusold/homebox-export/blob/main/README.md).
