# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: homebox-export
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/homebox-export
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers_v2:
  - dockerfile: Dockerfile
    images:
      - "ghcr.io/kusold/homebox-export"
    tags:
      - "v{{ .Version }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    extra_files: []

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - "zip"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: kusold
    name: homebox-export
  draft: true
  prerelease: auto
  mode: replace
  header: |
    ## homebox-export {{ .Version }} ({{ .Date }})

    See the full changelog [here](https://github.com/kusold/homebox-export/blob/main/CHANGELOG.md)

    ### Docker Images
    ```bash
    docker pull ghcr.io/kusold/homebox-export:{{ .Version }}
    ```
  footer: |
    **Full Changelog**: https://github.com/kusold/homebox-export/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Thanks!
    For more information, please check the [documentation](https://github.com/kusold/homebox-export/blob/main/README.md).
