version: "3"

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: clean
      - task: build
      - task: run

  run:
    cmds:
      - ./bin/homebox-export export -server ${HOMEBOX_SERVER} -user ${HOMEBOX_USER} -pass ${HOMEBOX_PASS} -output export

  build:
    cmds:
      - go build -o bin/homebox-export ./cmd/homebox-export

  clean:
    cmds:
      - rm -f bin/homebox-export
      - rm -rf export/*

  release:snapshot:
    cmds:
      - go run github.com/goreleaser/goreleaser/v2 --snapshot --clean --skip=publish

  release:
    cmds:
      - go run github.com/goreleaser/goreleaser/v2 --clean

  validate:codecov:
    cmds:
      - curl --data-binary @codecov.yaml https://codecov.io/validate
